import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import { Nav } from '../components/Nav';
import { Homepage } from '../components/Home/Homepage';
import { Slideshow } from '../components/Home/Slideshow';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Obsydia</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/public/favicon.ico" />
			</Head>
			<main className="flex flex-col min-h-screen border-4 bg-gray-800">
				<Nav />
				<Homepage />
				<Slideshow />
			</main>
		</>
	);
}
